name       : numpy
version    : 1.14.1
release    : 19
source     :
    - https://github.com/numpy/numpy/archive/v1.14.1.tar.gz : 3b10f4923c8073cd3fe2cf55b03e6e4723dc99cdb31e87beea666fef50fd32eb
license    : BSD-3-Clause
component  : programming.python
optimize   : speed
summary    : array processing for numbers, strings, records, and objects in Python
description: |
    NumPy is an array-processing package for Python designed to efficiently manipulate large multi-dimensional arrays of arbitrary records without the sacrifice of speed. It is built on the Numeric code base.
builddeps  :
    - cython
    - gfortran
    - python-setuptools
    - openblas-devel
setup      : |
    #Borrowed from Clear Linux
    %patch -p1 < $pkgfiles/build.patch
    %python_setup --fcompiler=gnu95
    %python3_setup --fcompiler=gnu95
install    : |
    %python_install
    %python3_install
