name       : numpy
version    : 1.9.2
release    : 5
source     :
    - http://internode.dl.sourceforge.net/project/numpy/NumPy/1.9.2/numpy-1.9.2.tar.gz : 325e5f2b0b434ecb6e6882c7e1034cc6cdde3eeeea87dbc482575199a6aeef2a
license    : BSD-3-Clause
summary    : array processing for numbers, strings, records, and objects in Python
description: |
    NumPy is an array-processing package for Python designed to efficiently manipulate large multi-dimensional arrays of arbitrary records without the sacrifice of speed. It is built on the Numeric code base.
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python-3.5)
build      : |
    for py in "python" "python3" ; do
        ${py} setup.py build
    done
install    : |
    for py in "python" "python3" ; do
        ${py} setup.py install --root=%installroot% --no-compile -O0
    done
