name       : numpy
version    : 1.22.4
release    : 36
source     :
    - https://github.com/numpy/numpy/releases/download/v1.22.4/numpy-1.22.4.tar.gz : b4308198d0e41efaa108e57d69973398439c7299a9d551680cdd603cf6d20709
license    : BSD-3-Clause
component  : programming.python
optimize   :
    - speed
    - lto
avx2       : yes
summary    : Array processing for numbers, strings, records, and objects in Python
description: |
    NumPy is an array-processing package for Python designed to efficiently manipulate large multi-dimensional arrays of arbitrary records without the sacrifice of speed. It is built on the Numeric code base.
builddeps  :
    - pkgconfig(openblas)
    - pkgconfig(lapack)
    - pkgconfig(x11)
    - cython
    - python-hypothesis
    - python-pytest
setup      : |
    %patch -p1 < $pkgfiles/0001-Ensure-SSE2-is-the-minimum-baseline.patch
build      : |
    %python3_setup --fcompiler=gnu95
install    : |
    %python3_install
#check      : |
#    %python3_test runtests.py
