name       : numpy
version    : 1.16.6
release    : 27
source     :
    - https://github.com/numpy/numpy/releases/download/v1.16.6/numpy-1.16.6.tar.gz : 61562ddac78765969959500b0da9c6f9ba7d77eeb12ec3927afae5303df08777
license    : BSD-3-Clause
component  : programming.python
optimize   : speed
summary    : Array processing for numbers, strings, records, and objects in Python
description: |
    NumPy is an array-processing package for Python designed to efficiently manipulate large multi-dimensional arrays of arbitrary records without the sacrifice of speed. It is built on the Numeric code base.
builddeps  :
    - cython
    - gfortran
    - pkgconfig(openblas)
    - pkgconfig(x11)
    - python-pytest
setup      : |
    %python_setup --fcompiler=gnu95
    %python3_setup --fcompiler=gnu95
install    : |
    %python_install
    %python3_install
# check      : |
    # python_test runtests.py --no-build
    # python3_test runtests.py --no-build
