name       : numpy
version    : 1.20.3
release    : 32
source     :
    - https://github.com/numpy/numpy/releases/download/v1.20.3/numpy-1.20.3.tar.gz : b7340f0628ce1823c151e3d2a2a8cba2a3ff1357fba4475a24b1816e75c21f90
license    : BSD-3-Clause
component  : programming.python
optimize   : speed
summary    : Array processing for numbers, strings, records, and objects in Python
description: |
    NumPy is an array-processing package for Python designed to efficiently manipulate large multi-dimensional arrays of arbitrary records without the sacrifice of speed. It is built on the Numeric code base.
builddeps  :
    - pkgconfig(openblas)
    - pkgconfig(x11)
    - cython
    - python-hypothesis
    - python-pytest
setup      : |
    %patch -p1 < $pkgfiles/0001-Ensure-SSE2-is-the-minimum-baseline.patch
build      : |
    %python3_setup --fcompiler=gnu95
install    : |
    %python3_install
#check      : |
#    %python3_test runtests.py
