name       : numpy
version    : 1.16.0
release    : 22
source     :
    - https://github.com/numpy/numpy/releases/download/v1.16.0/numpy-1.16.0.tar.gz : 9b98898687b5dd05c4ac7bcf7e8669a50dd2bb19591b772e045e5806c23e0ca4
license    : BSD-3-Clause
component  : programming.python
optimize   : speed
summary    : Array processing for numbers, strings, records, and objects in Python
description: |
    NumPy is an array-processing package for Python designed to efficiently manipulate large multi-dimensional arrays of arbitrary records without the sacrifice of speed. It is built on the Numeric code base.
builddeps  :
    - cython
    - gfortran
    - pkgconfig(openblas)
    - python-pytest
setup      : |
    #Borrowed from Clear Linux
    %patch -p1 < $pkgfiles/build.patch
    %python_setup --fcompiler=gnu95
    %python3_setup --fcompiler=gnu95
install    : |
    %python_install
    %python3_install
check      : |
    %python_test runtests.py --no-build
    %python3_test runtests.py --no-build
